### ISSUE TITLE
Hynia nie rabotaeet

### ISSUE THREAD

**Issue by Licomix** [FlacSy/BotArchitecture#1]
Peredelivay pidpr
![image](https://github.com/FlacSy/BotArchitecture/assets/59695075/4950fa98-66dc-49ab-a947-9a73cac2259c)

**Comment by FlacSy** [comment]
Простите за то что что-то не работает, пожалуйста укажите конкретные что у вас сломалось и я смогу это исправить.

**Comment by Licomix** [comment]
> Простите за то что что-то не работает, пожалуйста укажите конкретные что у вас сломалось и я смогу это исправить. 

Я скачал, поставил, оно не работать.![image](https://github.com/FlacSy/BotArchitecture/assets/59695075/25f37e8f-9c58-437a-a256-8da04ccbaa4e)
